### ISSUE TITLE
CPU usage too high

### ISSUE THREAD

**Issue by Rainbow87** [rockcarry/CameraDVR#1]
Hi CK,
i'm using CameraDVR app to preview camera, and i see that CPU usage is too high.
If only one Camera preview, CPU is about 25%, and if preview dual camera, CPU is double, over 50%!
![image](https://user-images.githubusercontent.com/13791476/35503842-e16b67bc-0513-11e8-81bc-ec043567ce92.png)
![image](https://user-images.githubusercontent.com/13791476/35503944-2e32fdc6-0514-11e8-8698-53dac5b1e77b.png)

How about it in your application?

**Comment by rockcarry** [comment]
CameraDVR is depending on the v4l2test project.

so the performance bottleneck is in v4l2test jni library. you need try do optimization in v4l2test.
